version: '3.7'

services:
  web:
    build: ./app
    command: sh -c "python salesloft_project/manage.py migrate &&
                                python salesloft_project/manage.py loaddata */fixtures/*.json  &&
                                python salesloft_project/manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      APIKEY_SALESLOFT: "${APIKEY_SALESLOFT}"
    depends_on:
      - db

  frontend:
    build: ./frontend
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - 4201:4200

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
