version: '3.7'

services:
  web:
    build: ./app
    command: python salesloft_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=salesloft
      - POSTGRES_PASSWORD=salesfot1234
      - POSTGRES_DB=salesloft_db

volumes:
  postgres_data:
