version: '3.7'

services:
  web:
    build: ./app
    command: python salesloft_project/manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      APIKEY_SALESLOFT: "${APIKEY_SALESLOFT}"
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db

volumes:
  postgres_data:
